/*
 * generated by Xtext 2.10.0
 */
package org.xtext.twitter.twt


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TwitterRESTAPIStandaloneSetup extends TwitterRESTAPIStandaloneSetupGenerated {

	def static void doSetup() {
		new TwitterRESTAPIStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
