<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="twitterRESTAPI" nsURI="http://www.example.org/twitterRESTAPI"
    nsPrefix="twitterRESTAPI">
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hashtag" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Date" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Deck">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//ExprBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExprBinaire" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp1" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp2" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//ExprBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Not">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="equals" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="lessThan" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExprSimple" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="upperThan" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="WebPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deck" lowerBound="1" upperBound="-1"
        eType="#//Deck" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
